# Generated by Django 5.2.16 on 2026-07-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
